### ISSUE TITLE
Concurrent modification exception

### ISSUE THREAD

**Issue by simon-greatrix** [simon-greatrix/sec-prng#2]
[PRNG-EntropyCollector-1] ERROR prng.collector.EntropyCollector - Error during entropy collection
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1493) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1516) ~[?:?]
	at prng.seeds.SeedStorage.getInstance(SeedStorage.java:166) ~[SecurePRNG-core-0.10.jar!/:?]
	at prng.seeds.SeedStorage.enqueue(SeedStorage.java:101) ~[SecurePRNG-core-0.10.jar!/:?]
	at prng.Fortuna.addEvent(Fortuna.java:171) ~[SecurePRNG-core-0.10.jar!/:?]
	at prng.EntropySource.post(EntropySource.java:66) ~[SecurePRNG-core-0.10.jar!/:?]
	at prng.EntropySource.setEvent(EntropySource.java:175) ~[SecurePRNG-core-0.10.jar!/:?]
	at prng.collector.SchedulingEntropy.runImpl(SchedulingEntropy.java:37) ~[SecurePRNG-core-0.10.jar!/:?]
	at prng.collector.EntropyCollector.run(EntropyCollector.java:336) [SecurePRNG-core-0.10.jar!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by simon-greatrix** [comment]
and again:

Exception in thread "PRNG-NetRandom" java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
	at prng.seeds.SeedStorage.getInstance(SeedStorage.java:182)
	at prng.internet.NetManager.init(NetManager.java:137)
	at prng.internet.NetManager.run(NetManager.java:190)
	at java.base/java.lang.Thread.run(Thread.java:834)
